version: '3'
services:
  backend:
    build: ./backend
    ports:
    - 9001:8080
    networks:
      - network-back
    depends_on:
      - "postgres-db"

  frontend:
    build: ./frontend
    ports: 
    - 9002:80
    networks:
      - network-front
      - network-back
 
  postgres-db:
    image: postgres:12.2
    container_name: postgres-db
    expose:
      - "5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - network-back
    environment:
      POSTGRES_DB: supersocial
      POSTGRES_USER: supersocial
      POSTGRES_PASSWORD: supersocial

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    expose:
      - "9200"
      - "9300"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - network-back
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  network-front:
    driver: bridge
  network-back:
    driver: bridge
 
volumes:
  db-data:
  elastic-data:
      